---
title: "Attendance Report"
# author: "Rob Creel"
# date: "January 7, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pdftools)
library(magrittr)
library(lubridate)
library(tibble)
library(dplyr)
library(ggplot2)

a0 <- "A00000"
df <- data.frame(Student=character(), 
                 Presence=character(), 
                 Date=character(), 
                 stringsAsFactors=FALSE) 

att <- pdf_text("Attendance Report.pdf") %>% strsplit(split = "\n")

header <- att[[1]][2]

for (i in 1:length(att)) {
  page <- att[[i]]
  for (j in 1:length(page)) {
    line <- page[[j]]
    linelist <- strsplit(line, "\\s+")[[1]]
    n <- length(linelist)
    if (!is.na(substr(linelist[5], 1, 6))){
      if (substr(linelist[n - 2], 1, 6) == a0) {
        if (linelist[6] == "Left") {
          new_row <- c(paste(linelist[2:3], collapse = " "), 
                       paste(linelist[(n - 2):(n - 1)], collapse = " "),
                       linelist[n])
        } else {
          new_row <- c(paste(linelist[2:3], collapse = " "), linelist[(n - 1):(n)])
        }
        df[nrow(df)+1,] <- new_row
      }
    }
  }
}


df$Date <- mdy(df$Date)

```

# Attendance Report for
## `r header`
Class has met `r length(unique(df$Date))` times so far. 

## Course attendance by date.

```{r by_date}
df %>% group_by(Date) %>% count(name = "total") -> date_df
df %>% group_by(Date) %>% filter(Presence == "Present" | Presence == "Late" | Presence == "Left Early") %>% count(name = "in_class") -> date_p_df
date_df %>% add_column(in_class = date_p_df$in_class) -> date_df
date_df %>% mutate(percent = in_class / total * 100) -> date_df

ggplot(date_df, aes(factor(Date), percent, group = 1)) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  xlab("Date")
```

## Course attendance by student.

```{r by_student}
df <- df %>% select(Date == max(Date))
df %>% group_by(Student) %>% filter(Presence == "Present" | Presence == "Late" | Presence == "Left Early") %>% count(name = "in_class") -> student_df
df %>% group_by(Student) %>% filter(Presence == "Absent") %>% count(name = "absent") -> student_a_df
# date_df %>% add_column(in_class = date_p_df$in_class) -> date_df
student_df %>% add_column(absent = student_a_df$absent) -> student_df
```